// ============================================================================
// SECTION: 30_data_tables.js
// PERIODS/BRANCHES/BUILTIN_EVENTS/PDF_TIMETABLES static data
// Source: index.html lines 3907-4919 (verbatim)
// NOTE: sections share one module scope after composition — plain code, no
// imports/exports here by design. Rebuild app.js after editing.
// ============================================================================

        // ========== DATA ==========
        const PERIODS = [
            { key: 'I', start: '09:10', end: '10:00', label: 'I' },
            { key: 'II', start: '10:00', end: '10:50', label: 'II' },
            { key: 'III', start: '10:50', end: '11:40', label: 'III' },
            { key: 'IV', start: '11:40', end: '12:30', label: 'IV' },
            { key: 'LUNCH', start: '12:30', end: '14:10', label: 'Lunch' },
            { key: 'V', start: '14:10', end: '15:00', label: 'V' },
            { key: 'VI', start: '15:00', end: '15:50', label: 'VI' },
            { key: 'VII', start: '15:50', end: '16:40', label: 'VII' },
            { key: 'VIII', start: '16:40', end: '17:30', label: 'VIII' },
        ];
        const TEACH_PERIODS = PERIODS.filter(p => p.key !== 'LUNCH');
        const DAYS = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'];
        const DAY_SHORT = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'];

        const BRANCHES = [
            { id: 'civil', name: 'B.Tech — Civil Engineering', sections: ['A', 'B'], room: 'TL-206',
                subjects: [
                    { code: 'BSM-110', name: 'Engineering Mathematics I', ltp: [3, 1, 0] },
                    { code: 'BSM-131', name: 'Engineering Physics', ltp: [3, 0, 2] },
                    { code: 'BIT-103', name: 'Programming in C', ltp: [3, 0, 2] },
                    { code: 'BCE-121', name: 'Engineering Graphics', ltp: [2, 0, 4] },
                    { code: 'BHS-101', name: 'Universal Human Values', ltp: [3, 1, 0] },
                ] },
            { id: 'cse', name: 'B.Tech — Computer Sc. & Engineering', sections: ['A', 'B', 'C', 'D'], room: 'TL-109 / TL-201',
                subjects: [
                    { code: 'BSM-110', name: 'Engineering Mathematics I', ltp: [3, 1, 0] },
                    { code: 'BSM-131', name: 'Engineering Physics', ltp: [3, 0, 2] },
                    { code: 'BCS-110', name: 'Introduction to C Programming', ltp: [3, 0, 2] },
                    { code: 'BCS-111', name: 'Web Designing-1', ltp: [2, 0, 4] },
                    { code: 'BHS-101', name: 'Universal Human Values', ltp: [3, 1, 0] },
                ] },
            { id: 'it', name: 'B.Tech — Information Technology', sections: ['A', 'B'], room: 'TL-203',
                subjects: [
                    { code: 'BSM-110', name: 'Engineering Mathematics I', ltp: [3, 1, 0] },
                    { code: 'BSM-131', name: 'Engineering Physics', ltp: [3, 0, 2] },
                    { code: 'BIT-103', name: 'Programming in C', ltp: [3, 0, 2] },
                    { code: 'BIT-104', name: 'Internet and Web Designing', ltp: [2, 0, 4] },
                    { code: 'BHS-101', name: 'Universal Human Values', ltp: [3, 1, 0] },
                ] },
            { id: 'chemical', name: 'B.Tech — Chemical Engineering', sections: ['A'], room: 'TL-110',
                subjects: [
                    { code: 'BSM-110', name: 'Engineering Mathematics I', ltp: [3, 1, 0] },
                    { code: 'BSM-131', name: 'Engineering Physics', ltp: [3, 0, 2] },
                    { code: 'BIT-103', name: 'Programming in C', ltp: [3, 0, 2] },
                    { code: 'BME-104', name: 'Manufacturing Techniques Workshop', ltp: [2, 0, 4] },
                    { code: 'BHS-101', name: 'Universal Human Values', ltp: [3, 1, 0] },
                ] },
            { id: 'ee', name: 'B.Tech — Electrical Engineering', sections: ['A', 'B'], room: 'TL-202',
                subjects: [
                    { code: 'BSM-110', name: 'Engineering Mathematics I', ltp: [3, 1, 0] },
                    { code: 'BSM-140', name: 'Environmental Science & Green Chemistry', ltp: [3, 0, 2] },
                    { code: 'BEE-110', name: 'Basic Electrical Engineering', ltp: [3, 0, 2] },
                    { code: 'BEE-108A', name: 'Electrical Wiring & Estimation', ltp: [3, 0, 2] },
                    { code: 'BHS-102', name: 'Technical Writing & Professional Communication', ltp: [2, 1, 2] },
                ] },
            { id: 'me', name: 'B.Tech — Mechanical Engineering', sections: ['A', 'B'], room: 'TL-205',
                subjects: [
                    { code: 'BSM-110', name: 'Engineering Mathematics I', ltp: [3, 1, 0] },
                    { code: 'BSM-140', name: 'Environmental Science & Green Chemistry', ltp: [3, 0, 2] },
                    { code: 'BEE-110', name: 'Basic Electrical Engineering', ltp: [3, 0, 2] },
                    { code: 'BME-104', name: 'Manufacturing Practice Workshop', ltp: [2, 0, 4] },
                    { code: 'BHS-102', name: 'Technical Writing & Professional Communication', ltp: [2, 1, 2] },
                ] },
            { id: 'ece', name: 'B.Tech — Electronics & Comm. Engineering', sections: ['A', 'B', 'C'], room: 'TL-207 / TL-204',
                subjects: [
                    { code: 'BSM-110', name: 'Engineering Mathematics I', ltp: [3, 1, 0] },
                    { code: 'BSM-140', name: 'Environmental Science & Green Chemistry', ltp: [3, 0, 2] },
                    { code: 'BEE-110', name: 'Basic Electrical Engineering', ltp: [3, 0, 2] },
                    { code: 'BEC-106', name: 'Electronic Components Testing & Measurement', ltp: [2, 0, 4] },
                    { code: 'BHS-102', name: 'Technical Writing & Professional Communication', ltp: [2, 1, 2] },
                ] },
            { id: 'eceiot', name: 'B.Tech - ECE (IOT)', sections: ['A'], room: 'TL-204',
                subjects: [
                    { code: 'BSM-110', name: 'Engineering Mathematics I', ltp: [3, 1, 0] },
                    { code: 'BSM-140', name: 'Environmental Science & Green Chemistry', ltp: [3, 0, 2] },
                    { code: 'BEE-110', name: 'Basic Electrical Engineering', ltp: [3, 0, 2] },
                    { code: 'BEC-106', name: 'Electronic Components Testing & Measurement', ltp: [2, 0, 4] },
                    { code: 'BHS-102', name: 'Technical Writing & Professional Communication', ltp: [2, 1, 2] },
                ] },
            { id: 'bba', name: 'BBA', sections: ['A', 'B'], room: 'TL-113 / TL-114',
                subjects: [
                    { code: 'BBA-114', name: 'Financial Accounting', ltp: [3, 0, 0] },
                    { code: 'BBA-115', name: 'Principles & Practices of Management', ltp: [3, 0, 0] },
                    { code: 'BBA-116', name: 'Quantitative Techniques for Business Research', ltp: [3, 0, 0] },
                    { code: 'BBA-A01', name: 'Business Communication for Managers', ltp: [2, 0, 0] },
                    { code: 'BHM-121', name: 'Industrial Psychology / IPR', ltp: [2, 0, 0] },
                    { code: 'AUC-108', name: 'Ability / Value Added Course', ltp: [2, 0, 0] },
                ] },
            { id: 'bpharm', name: 'B.Pharm', sections: ['A'], room: 'L-115',
                subjects: [
                    { code: 'BPT101T', name: 'Human Anatomy, Physiology & Pathophysiology I', ltp: [3, 0, 0] },
                    { code: 'BPT102T', name: 'Introduction to Pharmacognosy', ltp: [3, 0, 0] },
                    { code: 'BPT103T', name: 'Pharmaceutical Inorganic & Analytical Chemistry', ltp: [3, 0, 0] },
                    { code: 'BPT104T', name: 'Basics of Python Programming', ltp: [2, 0, 0] },
                    { code: 'BPT105T', name: 'General Pharmacy', ltp: [2, 0, 0] },
                    { code: 'BPT106T', name: 'Healthcare Psychology & Communication Skills', ltp: [2, 0, 0] },
                    { code: 'BPT107P', name: 'Pharmacognosy (Practical)', ltp: [0, 0, 2] },
                    { code: 'BPT108P', name: 'Inorganic & Analytical Chemistry (Practical)', ltp: [0, 0, 2] },
                    { code: 'BPT109P', name: 'General Pharmacy (Practical)', ltp: [0, 0, 2] },
                    { code: 'BPT110P', name: 'Healthcare Psychology (Practical)', ltp: [0, 0, 2] },
                    { code: 'BPT111P', name: 'Anatomy & Physiology (Practical)', ltp: [0, 0, 2] },
                ] },
        ];

        const BUILTIN_EVENTS = [
            { start: '2026-07-29', end: '2026-07-30', title: 'Physical Reporting at MMMUT Gorakhpur' },
            { start: '2026-07-31', end: '2026-07-31', title: 'Orientation Program' },
            { start: '2026-08-01', end: '2026-08-22', title: 'Induction Program for Newly Admitted Students (IPNS-2026)' },
            { start: '2026-08-03', end: '2026-08-03', title: 'Commencement of classes (partially)' },
            { start: '2026-09-18', end: '2026-09-18', title: 'Display of Mid Semester Attendance by HoD' },
            { start: '2026-09-21', end: '2026-09-25', title: 'Minor Test Examination' },
            { start: '2026-11-09', end: '2026-11-16', title: 'Mid Semester Break' },
            { start: '2026-11-21', end: '2026-11-22', title: 'Alumni Meet' },
            { start: '2026-11-23', end: '2026-11-23', title: 'Last date for end semester classes' },
            { start: '2026-11-24', end: '2026-11-27', title: 'Practical Exam / Doubt Clearing classes' },
            { start: '2026-11-26', end: '2026-11-26', title: 'Display of attendance by Dean Office' },
            { start: '2026-11-30', end: '2026-12-08', title: 'End Semester Major Examination' },
            { start: '2026-12-01', end: '2026-12-01', title: 'University Foundation Day' },
            { start: '2026-12-09', end: '2026-12-12', title: 'Semester Break' },
            { start: '2026-12-12', end: '2026-12-12', title: 'Last date for evaluation of answer sheets & marks uploading' },
            { start: '2026-12-14', end: '2026-12-14', title: 'Last date for grade moderation committee meeting (1st Year)' },
            { start: '2026-12-15', end: '2026-12-15', title: 'Last date for declaration of semester result' },
            { start: '2026-12-09', end: '2026-12-12', title: 'Online registration (Even Semester)' },
            { start: '2026-12-14', end: '2026-12-14', title: 'Commencement of classes (Even Semester)' },
            { start: '2026-12-18', end: '2026-12-20', title: 'CSA Activity — Tech Srijan' },
            { start: '2027-01-30', end: '2027-01-30', title: 'Display of Mid Semester Attendance by HoD' },
            { start: '2027-02-01', end: '2027-02-06', title: 'Minor Test Examination' },
            { start: '2027-02-12', end: '2027-02-13', title: 'CSA Activity — Annual Sports Meet' },
            { start: '2027-02-26', end: '2027-02-28', title: 'CSA Activity — Cultural Program' },
            { start: '2027-03-22', end: '2027-03-27', title: 'Mid Semester Break' },
            { start: '2027-04-17', end: '2027-04-17', title: 'Last date for end semester classes' },
            { start: '2027-04-19', end: '2027-04-24', title: 'Practical Exam / Doubt Clearing classes' },
            { start: '2027-04-22', end: '2027-04-22', title: 'Display of attendance by Dean Office' },
            { start: '2027-04-26', end: '2027-05-05', title: 'End Semester Major Examination' },
            { start: '2027-05-05', end: '2027-06-30', title: 'Session Break' },
            { start: '2027-05-10', end: '2027-05-10', title: 'Last date for evaluation of answer sheets & marks uploading' },
            { start: '2027-05-12', end: '2027-05-12', title: 'Grade moderation committee meeting (1st Year)' },
            { start: '2027-05-07', end: '2027-05-14', title: 'Social Work / Training — Dean of Extension' },
            { start: '2027-05-13', end: '2027-05-13', title: 'Last date for declaration of semester result' },
            { start: '2027-05-16', end: '2027-06-14', title: 'Summer Break for Teachers' },
            { start: '2027-07-01', end: '2027-07-10', title: 'Online registration & fee deposit — Second Year' },
        ];

        const PDF_TIMETABLES = {
            "civil::A": { "Monday": { "I": { "code": "BSM-131", "name": "Engineering Physics", "type": "Lecture" },
                    "II": { "code": "BSM-110", "name": "Engineering Mathematics I", "type": "Lecture" },
                    "III": { "code": "BIT-103", "name": "Programming in C", "type": "Lecture" },
                    "IV": { "code": "BCE-121", "name": "Engineering Graphics", "type": "Lecture" },
                    "V": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "VI": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "VII": { "code": "BHS-101", "name": "Universal Human Values", "type": "Lecture" },
                    "VIII": { "code": "BSM-110", "name": "Engineering Mathematics I", "type": "Tutorial" } },
                "Tuesday": { "I": { "code": "BSM-131", "name": "Engineering Physics", "type": "Lecture" },
                    "II": { "code": "BSM-110", "name": "Engineering Mathematics I", "type": "Lecture" },
                    "III": { "code": "BHS-101", "name": "Universal Human Values", "type": "Tutorial" },
                    "IV": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "V": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "VI": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "VII": { "code": "BSM-110", "name": "Engineering Mathematics I", "type": "Tutorial" },
                    "VIII": { "code": "—", "name": "Self Study / Library", "type": "Free" } },
                "Wednesday": { "I": { "code": "BSM-131", "name": "Engineering Physics", "type": "Lecture" },
                    "II": { "code": "BSM-110", "name": "Engineering Mathematics I", "type": "Lecture" },
                    "III": { "code": "BHS-101", "name": "Universal Human Values", "type": "Tutorial" },
                    "IV": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "V": { "code": "BSM-131", "name": "Engineering Physics", "type": "Practical" },
                    "VI": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "VII": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "VIII": { "code": "—", "name": "Self Study / Library", "type": "Free" } },
                "Thursday": { "I": { "code": "BIT-103", "name": "Programming in C", "type": "Practical" },
                    "II": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "III": { "code": "BIT-103", "name": "Programming in C", "type": "Lecture" },
                    "IV": { "code": "BHS-101", "name": "Universal Human Values", "type": "Lecture" },
                    "V": { "code": "BSM-131", "name": "Engineering Physics", "type": "Practical" },
                    "VI": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "VII": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "VIII": { "code": "—", "name": "Self Study / Library", "type": "Free" } },
                "Friday": { "I": { "code": "BIT-103", "name": "Programming in C", "type": "Practical" },
                    "II": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "III": { "code": "BIT-103", "name": "Programming in C", "type": "Lecture" },
                    "IV": { "code": "BHS-101", "name": "Universal Human Values", "type": "Lecture" },
                    "V": { "code": "BCE-121", "name": "Engineering Graphics", "type": "Lecture" },
                    "VI": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "VII": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "VIII": { "code": "—", "name": "Self Study / Library", "type": "Free" } } },
            "cse::A": { "Monday": { "I": { "code": "BSM-131", "name": "Engineering Physics", "type": "Practical" },
                    "II": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "III": { "code": "BSM-131", "name": "Engineering Physics", "type": "Lecture" },
                    "IV": { "code": "BHS-101", "name": "Universal Human Values", "type": "Lecture" },
                    "V": { "code": "BCS-110", "name": "Introduction to C Programming", "type": "Practical" },
                    "VI": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "VII": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "VIII": { "code": "—", "name": "Self Study / Library", "type": "Free" } },
                "Tuesday": { "I": { "code": "BSM-131", "name": "Engineering Physics", "type": "Practical" },
                    "II": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "III": { "code": "BSM-131", "name": "Engineering Physics", "type": "Lecture" },
                    "IV": { "code": "BCS-111", "name": "Web Designing-1", "type": "Lecture" },
                    "V": { "code": "BCS-110", "name": "Introduction to C Programming", "type": "Practical" },
                    "VI": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "VII": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "VIII": { "code": "—", "name": "Self Study / Library", "type": "Free" } },
                "Wednesday": { "I": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "II": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "III": { "code": "BSM-131", "name": "Engineering Physics", "type": "Lecture" },
                    "IV": { "code": "BCS-111", "name": "Web Designing-1", "type": "Lecture" },
                    "V": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "VI": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "VII": { "code": "BSM-110", "name": "Engineering Mathematics I", "type": "Lecture" },
                    "VIII": { "code": "BCS-110", "name": "Introduction to C Programming", "type": "Lecture" } },
                "Thursday": { "I": { "code": "BSM-110", "name": "Engineering Mathematics I", "type": "Lecture" },
                    "II": { "code": "BCS-110", "name": "Introduction to C Programming", "type": "Lecture" },
                    "III": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "IV": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "V": { "code": "BSM-110", "name": "Engineering Mathematics I", "type": "Tutorial" },
                    "VI": { "code": "BHS-101", "name": "Universal Human Values", "type": "Lecture" },
                    "VII": { "code": "BHS-101", "name": "Universal Human Values", "type": "Tutorial" },
                    "VIII": { "code": "—", "name": "Self Study / Library", "type": "Free" } },
                "Friday": { "I": { "code": "BSM-110", "name": "Engineering Mathematics I", "type": "Lecture" },
                    "II": { "code": "BCS-110", "name": "Introduction to C Programming", "type": "Lecture" },
                    "III": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "IV": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "V": { "code": "BHS-101", "name": "Universal Human Values", "type": "Lecture" },
                    "VI": { "code": "BSM-110", "name": "Engineering Mathematics I", "type": "Tutorial" },
                    "VII": { "code": "BHS-101", "name": "Universal Human Values", "type": "Tutorial" },
                    "VIII": { "code": "—", "name": "Self Study / Library", "type": "Free" } } },
            "cse::B": { "Monday": { "I": { "code": "BSM-110", "name": "Engineering Mathematics I", "type": "Lecture" },
                    "II": { "code": "BCS-110", "name": "Introduction to C Programming", "type": "Lecture" },
                    "III": { "code": "BCS-110", "name": "Introduction to C Programming", "type": "Practical" },
                    "IV": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "V": { "code": "BSM-110", "name": "Engineering Mathematics I", "type": "Tutorial" },
                    "VI": { "code": "BHS-101", "name": "Universal Human Values", "type": "Lecture" },
                    "VII": { "code": "BHS-101", "name": "Universal Human Values", "type": "Tutorial" },
                    "VIII": { "code": "—", "name": "Self Study / Library", "type": "Free" } },
                "Tuesday": { "I": { "code": "BSM-110", "name": "Engineering Mathematics I", "type": "Lecture" },
                    "II": { "code": "BCS-110", "name": "Introduction to C Programming", "type": "Lecture" },
                    "III": { "code": "BCS-110", "name": "Introduction to C Programming", "type": "Practical" },
                    "IV": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "V": { "code": "BHS-101", "name": "Universal Human Values", "type": "Lecture" },
                    "VI": { "code": "BSM-110", "name": "Engineering Mathematics I", "type": "Tutorial" },
                    "VII": { "code": "BHS-101", "name": "Universal Human Values", "type": "Tutorial" },
                    "VIII": { "code": "—", "name": "Self Study / Library", "type": "Free" } },
                "Wednesday": { "I": { "code": "BSM-110", "name": "Engineering Mathematics I", "type": "Lecture" },
                    "II": { "code": "BCS-110", "name": "Introduction to C Programming", "type": "Lecture" },
                    "III": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "IV": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "V": { "code": "BSM-131", "name": "Engineering Physics", "type": "Lecture" },
                    "VI": { "code": "BCS-111", "name": "Web Designing-1", "type": "Lecture" },
                    "VII": { "code": "BSM-131", "name": "Engineering Physics", "type": "Practical" },
                    "VIII": { "code": "—", "name": "Self Study / Library", "type": "Free" } },
                "Thursday": { "I": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "II": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "III": { "code": "BSM-131", "name": "Engineering Physics", "type": "Lecture" },
                    "IV": { "code": "BCS-111", "name": "Web Designing-1", "type": "Lecture" },
                    "V": { "code": "BCS-111", "name": "Web Designing-1", "type": "Practical" },
                    "VI": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "VII": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "VIII": { "code": "—", "name": "Self Study / Library", "type": "Free" } },
                "Friday": { "I": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "II": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "III": { "code": "BSM-131", "name": "Engineering Physics", "type": "Lecture" },
                    "IV": { "code": "BCS-111", "name": "Web Designing-1", "type": "Lecture" },
                    "V": { "code": "BSM-131", "name": "Engineering Physics", "type": "Practical" },
                    "VI": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "VII": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "VIII": { "code": "—", "name": "Self Study / Library", "type": "Free" } } },
            "cse::C": { "Monday": { "I": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "II": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "III": { "code": "BSM-110", "name": "Engineering Mathematics I", "type": "Lecture" },
                    "IV": { "code": "BSM-131", "name": "Engineering Physics", "type": "Lecture" },
                    "V": { "code": "BCS-110", "name": "Introduction to C Programming", "type": "Lecture" },
                    "VI": { "code": "BSM-110", "name": "Engineering Mathematics I", "type": "Tutorial" },
                    "VII": { "code": "BHS-101", "name": "Universal Human Values", "type": "Tutorial" },
                    "VIII": { "code": "—", "name": "Self Study / Library", "type": "Free" } },
                "Tuesday": { "I": { "code": "BCS-111", "name": "Web Designing-1", "type": "Practical" },
                    "II": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "III": { "code": "BCS-110", "name": "Introduction to C Programming", "type": "Practical" },
                    "IV": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "V": { "code": "BHS-101", "name": "Universal Human Values", "type": "Lecture" },
                    "VI": { "code": "BSM-110", "name": "Engineering Mathematics I", "type": "Tutorial" },
                    "VII": { "code": "BHS-101", "name": "Universal Human Values", "type": "Tutorial" },
                    "VIII": { "code": "—", "name": "Self Study / Library", "type": "Free" } },
                "Wednesday": { "I": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "II": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "III": { "code": "BSM-110", "name": "Engineering Mathematics I", "type": "Lecture" },
                    "IV": { "code": "BSM-131", "name": "Engineering Physics", "type": "Lecture" },
                    "V": { "code": "BCS-111", "name": "Web Designing-1", "type": "Practical" },
                    "VI": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "VII": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "VIII": { "code": "—", "name": "Self Study / Library", "type": "Free" } },
                "Thursday": { "I": { "code": "BCS-111", "name": "Web Designing-1", "type": "Lecture" },
                    "II": { "code": "BCS-110", "name": "Introduction to C Programming", "type": "Lecture" },
                    "III": { "code": "BSM-131", "name": "Engineering Physics", "type": "Practical" },
                    "IV": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "V": { "code": "BHS-101", "name": "Universal Human Values", "type": "Lecture" },
                    "VI": { "code": "BSM-131", "name": "Engineering Physics", "type": "Lecture" },
                    "VII": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "VIII": { "code": "—", "name": "Self Study / Library", "type": "Free" } },
                "Friday": { "I": { "code": "BCS-111", "name": "Web Designing-1", "type": "Lecture" },
                    "II": { "code": "BCS-110", "name": "Introduction to C Programming", "type": "Lecture" },
                    "III": { "code": "BSM-131", "name": "Engineering Physics", "type": "Practical" },
                    "IV": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "V": { "code": "BHS-101", "name": "Universal Human Values", "type": "Lecture" },
                    "VI": { "code": "BSM-110", "name": "Engineering Mathematics I", "type": "Lecture" },
                    "VII": { "code": "BCS-110", "name": "Introduction to C Programming", "type": "Practical" },
                    "VIII": { "code": "—", "name": "Self Study / Library", "type": "Free" } } },
            "cse::D": { "Monday": { "I": { "code": "BHS-101", "name": "Universal Human Values", "type": "Lecture" },
                    "II": { "code": "BCS-110", "name": "Introduction to C Programming", "type": "Lecture" },
                    "III": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "IV": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "V": { "code": "BSM-131", "name": "Engineering Physics", "type": "Practical" },
                    "VI": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "VII": { "code": "BCS-110", "name": "Introduction to C Programming", "type": "Practical" },
                    "VIII": { "code": "—", "name": "Self Study / Library", "type": "Free" } },
                "Tuesday": { "I": { "code": "BCS-110", "name": "Introduction to C Programming", "type": "Lecture" },
                    "II": { "code": "BCS-111", "name": "Web Designing-1", "type": "Lecture" },
                    "III": { "code": "BSM-110", "name": "Engineering Mathematics I", "type": "Lecture" },
                    "IV": { "code": "BSM-131", "name": "Engineering Physics", "type": "Lecture" },
                    "V": { "code": "BCS-111", "name": "Web Designing-1", "type": "Practical" },
                    "VI": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "VII": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "VIII": { "code": "—", "name": "Self Study / Library", "type": "Free" } },
                "Wednesday": { "I": { "code": "BCS-110", "name": "Introduction to C Programming", "type": "Lecture" },
                    "II": { "code": "BCS-111", "name": "Web Designing-1", "type": "Lecture" },
                    "III": { "code": "BSM-131", "name": "Engineering Physics", "type": "Practical" },
                    "IV": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "V": { "code": "BCS-110", "name": "Introduction to C Programming", "type": "Practical" },
                    "VI": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "VII": { "code": "BHS-101", "name": "Universal Human Values", "type": "Lecture" },
                    "VIII": { "code": "BSM-110", "name": "Engineering Mathematics I", "type": "Tutorial" } },
                "Thursday": { "I": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "II": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "III": { "code": "BSM-110", "name": "Engineering Mathematics I", "type": "Lecture" },
                    "IV": { "code": "BSM-131", "name": "Engineering Physics", "type": "Lecture" },
                    "V": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "VI": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "VII": { "code": "BHS-101", "name": "Universal Human Values", "type": "Lecture" },
                    "VIII": { "code": "BHS-101", "name": "Universal Human Values", "type": "Tutorial" } },
                "Friday": { "I": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "II": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "III": { "code": "BSM-110", "name": "Engineering Mathematics I", "type": "Lecture" },
                    "IV": { "code": "BSM-131", "name": "Engineering Physics", "type": "Lecture" },
                    "V": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "VI": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "VII": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "VIII": { "code": "BHS-101", "name": "Universal Human Values", "type": "Tutorial" } } },
            "it::A": { "Monday": { "I": { "code": "BIT-103", "name": "Programming in C", "type": "Practical" },
                    "II": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "III": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "IV": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "V": { "code": "BHS-101", "name": "Universal Human Values", "type": "Lecture" },
                    "VI": { "code": "BSM-131", "name": "Engineering Physics", "type": "Lecture" },
                    "VII": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "VIII": { "code": "—", "name": "Self Study / Library", "type": "Free" } },
                "Tuesday": { "I": { "code": "BIT-103", "name": "Programming in C", "type": "Practical" },
                    "II": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "III": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "IV": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "V": { "code": "BHS-101", "name": "Universal Human Values", "type": "Lecture" },
                    "VI": { "code": "BSM-131", "name": "Engineering Physics", "type": "Lecture" },
                    "VII": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "VIII": { "code": "—", "name": "Self Study / Library", "type": "Free" } },
                "Wednesday": { "I": { "code": "BSM-110", "name": "Engineering Mathematics I", "type": "Lecture" },
                    "II": { "code": "BIT-103", "name": "Programming in C", "type": "Lecture" },
                    "III": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "IV": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "V": { "code": "BIT-104", "name": "Internet and Web Designing", "type": "Lecture" },
                    "VI": { "code": "BSM-110", "name": "Engineering Mathematics I", "type": "Tutorial" },
                    "VII": { "code": "BSM-131", "name": "Engineering Physics", "type": "Practical" },
                    "VIII": { "code": "—", "name": "Self Study / Library", "type": "Free" } },
                "Thursday": { "I": { "code": "BSM-110", "name": "Engineering Mathematics I", "type": "Lecture" },
                    "II": { "code": "BIT-103", "name": "Programming in C", "type": "Lecture" },
                    "III": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "IV": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "V": { "code": "BSM-110", "name": "Engineering Mathematics I", "type": "Tutorial" },
                    "VI": { "code": "BHS-101", "name": "Universal Human Values", "type": "Lecture" },
                    "VII": { "code": "BIT-104", "name": "Internet and Web Designing", "type": "Lecture" },
                    "VIII": { "code": "BHS-101", "name": "Universal Human Values", "type": "Tutorial" } },
                "Friday": { "I": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "II": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "III": { "code": "BSM-131", "name": "Engineering Physics", "type": "Lecture" },
                    "IV": { "code": "BIT-103", "name": "Programming in C", "type": "Lecture" },
                    "V": { "code": "BHS-101", "name": "Universal Human Values", "type": "Tutorial" },
                    "VI": { "code": "BSM-110", "name": "Engineering Mathematics I", "type": "Lecture" },
                    "VII": { "code": "BSM-131", "name": "Engineering Physics", "type": "Practical" },
                    "VIII": { "code": "—", "name": "Self Study / Library", "type": "Free" } } },
            "it::B": { "Monday": { "I": { "code": "BSM-110", "name": "Engineering Mathematics I", "type": "Lecture" },
                    "II": { "code": "BIT-103", "name": "Programming in C", "type": "Lecture" },
                    "III": { "code": "BSM-131", "name": "Engineering Physics", "type": "Lecture" },
                    "IV": { "code": "BHS-101", "name": "Universal Human Values", "type": "Lecture" },
                    "V": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "VI": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "VII": { "code": "BHS-101", "name": "Universal Human Values", "type": "Lecture" },
                    "VIII": { "code": "—", "name": "Self Study / Library", "type": "Free" } },
                "Tuesday": { "I": { "code": "BSM-110", "name": "Engineering Mathematics I", "type": "Lecture" },
                    "II": { "code": "BIT-103", "name": "Programming in C", "type": "Lecture" },
                    "III": { "code": "BSM-131", "name": "Engineering Physics", "type": "Lecture" },
                    "IV": { "code": "BIT-104", "name": "Internet and Web Designing", "type": "Lecture" },
                    "V": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "VI": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "VII": { "code": "BHS-101", "name": "Universal Human Values", "type": "Tutorial" },
                    "VIII": { "code": "BSM-110", "name": "Engineering Mathematics I", "type": "Tutorial" } },
                "Wednesday": { "I": { "code": "BSM-131", "name": "Engineering Physics", "type": "Practical" },
                    "II": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "III": { "code": "BSM-131", "name": "Engineering Physics", "type": "Lecture" },
                    "IV": { "code": "BHS-101", "name": "Universal Human Values", "type": "Lecture" },
                    "V": { "code": "BIT-103", "name": "Programming in C", "type": "Practical" },
                    "VI": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "VII": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "VIII": { "code": "—", "name": "Self Study / Library", "type": "Free" } },
                "Thursday": { "I": { "code": "BSM-131", "name": "Engineering Physics", "type": "Practical" },
                    "II": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "III": { "code": "BSM-110", "name": "Engineering Mathematics I", "type": "Lecture" },
                    "IV": { "code": "BHS-101", "name": "Universal Human Values", "type": "Tutorial" },
                    "V": { "code": "BIT-104", "name": "Internet and Web Designing", "type": "Practical" },
                    "VI": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "VII": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "VIII": { "code": "—", "name": "Self Study / Library", "type": "Free" } },
                "Friday": { "I": { "code": "BIT-103", "name": "Programming in C", "type": "Lecture" },
                    "II": { "code": "TL-203", "name": "TL-203", "type": "Tutorial" },
                    "III": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "IV": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "V": { "code": "BIT-103", "name": "Programming in C", "type": "Practical" },
                    "VI": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "VII": { "code": "BIT-104", "name": "Internet and Web Designing", "type": "Lecture" },
                    "VIII": { "code": "—", "name": "Self Study / Library", "type": "Free" } } },
            "chemical::A": { "Monday": { "I": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "II": { "code": "BSM-131", "name": "Engineering Physics", "type": "Lecture" },
                    "III": { "code": "BSM-110", "name": "Engineering Mathematics I", "type": "Lecture" },
                    "IV": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "V": { "code": "BME-101", "name": "Manufacturing Techniques Workshop", "type": "Lecture" },
                    "VI": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "VII": { "code": "BSM-131", "name": "Engineering Physics", "type": "Practical" },
                    "VIII": { "code": "—", "name": "Self Study / Library", "type": "Free" } },
                "Tuesday": { "I": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "II": { "code": "BSM-131", "name": "Engineering Physics", "type": "Lecture" },
                    "III": { "code": "BSM-110", "name": "Engineering Mathematics I", "type": "Lecture" },
                    "IV": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "V": { "code": "BSM-131", "name": "Engineering Physics", "type": "Practical" },
                    "VI": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "VII": { "code": "TL-110", "name": "TL-110", "type": "Tutorial" },
                    "VIII": { "code": "—", "name": "Self Study / Library", "type": "Free" } },
                "Wednesday": { "I": { "code": "BIT-103", "name": "Programming in C", "type": "Practical" },
                    "II": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "III": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "IV": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "V": { "code": "BHS-101", "name": "Universal Human Values", "type": "Lecture" },
                    "VI": { "code": "BIT-103", "name": "Programming in C", "type": "Lecture" },
                    "VII": { "code": "BHS-101", "name": "Universal Human Values", "type": "Tutorial" },
                    "VIII": { "code": "—", "name": "Self Study / Library", "type": "Free" } },
                "Thursday": { "I": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "II": { "code": "BSM-131", "name": "Engineering Physics", "type": "Lecture" },
                    "III": { "code": "BHS-101", "name": "Universal Human Values", "type": "Lecture" },
                    "IV": { "code": "BIT-103", "name": "Programming in C", "type": "Lecture" },
                    "V": { "code": "BME-104", "name": "Manufacturing Practice Workshop", "type": "Practical" },
                    "VI": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "VII": { "code": "BIT-103", "name": "Programming in C", "type": "Practical" },
                    "VIII": { "code": "—", "name": "Self Study / Library", "type": "Free" } },
                "Friday": { "I": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "II": { "code": "BSM-110", "name": "Engineering Mathematics I", "type": "Lecture" },
                    "III": { "code": "BHS-101", "name": "Universal Human Values", "type": "Lecture" },
                    "IV": { "code": "BIT-103", "name": "Programming in C", "type": "Lecture" },
                    "V": { "code": "BME-101", "name": "Manufacturing Techniques Workshop", "type": "Lecture" },
                    "VI": { "code": "TL-110", "name": "TL-110", "type": "Tutorial" },
                    "VII": { "code": "BHS-101", "name": "Universal Human Values", "type": "Tutorial" },
                    "VIII": { "code": "—", "name": "Self Study / Library", "type": "Free" } } },
            "ee::A": { "Monday": { "I": { "code": "BSM-140", "name": "Environmental Science & Green Chemistry",
                        "type": "Lecture" },
                    "II": { "code": "BSM-110", "name": "Engineering Mathematics I", "type": "Lecture" },
                    "III": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "IV": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "V": { "code": "BEE-108A", "name": "Electrical Wiring & Estimation", "type": "Practical" },
                    "VI": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "VII": { "code": "BHS-102", "name": "Technical Writing & Professional Communication",
                        "type": "Tutorial" },
                    "VIII": { "code": "—", "name": "Self Study / Library", "type": "Free" } },
                "Tuesday": { "I": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "II": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "III": { "code": "BEE-110", "name": "Basic Electrical Engineering", "type": "Lecture" },
                    "IV": { "code": "BHS-102", "name": "Technical Writing & Professional Communication",
                        "type": "Lecture" },
                    "V": { "code": "BEE-108A", "name": "Electrical Wiring & Estimation", "type": "Practical" },
                    "VI": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "VII": { "code": "BHS-102", "name": "Technical Writing & Professional Communication",
                        "type": "Lecture" },
                    "VIII": { "code": "—", "name": "Self Study / Library", "type": "Free" } },
                "Wednesday": { "I": { "code": "BHS-102", "name": "Technical Writing & Professional Communication",
                        "type": "Practical" },
                    "II": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "III": { "code": "BEE-110", "name": "Basic Electrical Engineering", "type": "Lecture" },
                    "IV": { "code": "BEE-108A", "name": "Electrical Wiring & Estimation", "type": "Lecture" },
                    "V": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "VI": { "code": "BSM-110", "name": "Engineering Mathematics I", "type": "Tutorial" },
                    "VII": { "code": "BHS-102", "name": "Technical Writing & Professional Communication",
                        "type": "Practical" },
                    "VIII": { "code": "—", "name": "Self Study / Library", "type": "Free" } },
                "Thursday": { "I": { "code": "BSM-140", "name": "Environmental Science & Green Chemistry",
                        "type": "Lecture" },
                    "II": { "code": "BSM-110", "name": "Engineering Mathematics I", "type": "Lecture" },
                    "III": { "code": "BSM-140", "name": "Environmental Science & Green Chemistry",
                        "type": "Practical" },
                    "IV": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "V": { "code": "BSM-110", "name": "Engineering Mathematics I", "type": "Tutorial" },
                    "VI": { "code": "BEE-110", "name": "Basic Electrical Engineering", "type": "Lecture" },
                    "VII": { "code": "BEE-108A", "name": "Electrical Wiring & Estimation", "type": "Lecture" },
                    "VIII": { "code": "—", "name": "Self Study / Library", "type": "Free" } },
                "Friday": { "I": { "code": "BSM-140", "name": "Environmental Science & Green Chemistry",
                        "type": "Lecture" },
                    "II": { "code": "BSM-110", "name": "Engineering Mathematics I", "type": "Lecture" },
                    "III": { "code": "BSM-140", "name": "Environmental Science & Green Chemistry",
                        "type": "Practical" },
                    "IV": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "V": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "VI": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "VII": { "code": "BEE-108A", "name": "Electrical Wiring & Estimation", "type": "Lecture" },
                    "VIII": { "code": "—", "name": "Self Study / Library", "type": "Free" } } },
            "ee::B": { "Monday": { "I": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "II": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "III": { "code": "BEE-108A", "name": "Electrical Wiring & Estimation", "type": "Lecture" },
                    "IV": { "code": "BEE-110", "name": "Basic Electrical Engineering", "type": "Lecture" },
                    "V": { "code": "BSM-110", "name": "Engineering Mathematics I", "type": "Tutorial" },
                    "VI": { "code": "BHS-102", "name": "Technical Writing & Professional Communication",
                        "type": "Tutorial" },
                    "VII": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "VIII": { "code": "—", "name": "Self Study / Library", "type": "Free" } },
                "Tuesday": { "I": { "code": "BSM-140", "name": "Environmental Science & Green Chemistry",
                        "type": "Lecture" },
                    "II": { "code": "BSM-110", "name": "Engineering Mathematics I", "type": "Lecture" },
                    "III": { "code": "BEE-110", "name": "Basic Electrical Engineering", "type": "Practical" },
                    "IV": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "V": { "code": "BSM-110", "name": "Engineering Mathematics I", "type": "Tutorial" },
                    "VI": { "code": "BEE-108A", "name": "Electrical Wiring & Estimation", "type": "Lecture" },
                    "VII": { "code": "BHS-102", "name": "Technical Writing & Professional Communication",
                        "type": "Practical" },
                    "VIII": { "code": "—", "name": "Self Study / Library", "type": "Free" } },
                "Wednesday": { "I": { "code": "BSM-140", "name": "Environmental Science & Green Chemistry",
                        "type": "Lecture" },
                    "II": { "code": "BSM-110", "name": "Engineering Mathematics I", "type": "Lecture" },
                    "III": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "IV": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "V": { "code": "BHS-102", "name": "Technical Writing & Professional Communication",
                        "type": "Lecture" },
                    "VI": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "VII": { "code": "BSM-140", "name": "Environmental Science & Green Chemistry",
                        "type": "Practical" },
                    "VIII": { "code": "—", "name": "Self Study / Library", "type": "Free" } },
                "Thursday": { "I": { "code": "BEE-108A", "name": "Electrical Wiring & Estimation", "type": "Practical" },
                    "II": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "III": { "code": "BEE-110", "name": "Basic Electrical Engineering", "type": "Lecture" },
                    "IV": { "code": "BHS-102", "name": "Technical Writing & Professional Communication",
                        "type": "Lecture" },
                    "V": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "VI": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "VII": { "code": "BSM-140", "name": "Environmental Science & Green Chemistry",
                        "type": "Practical" },
                    "VIII": { "code": "BHS-102", "name": "Technical Writing & Professional Communication",
                        "type": "Tutorial" } },
                "Friday": { "I": { "code": "BEE-108A", "name": "Electrical Wiring & Estimation", "type": "Practical" },
                    "II": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "III": { "code": "BSM-140", "name": "Environmental Science & Green Chemistry",
                    "type": "Lecture" },
                    "IV": { "code": "BSM-110", "name": "Engineering Mathematics I", "type": "Lecture" },
                    "V": { "code": "BEE-108A", "name": "Electrical Wiring & Estimation", "type": "Lecture" },
                    "VI": { "code": "BEE-110", "name": "Basic Electrical Engineering", "type": "Lecture" },
                    "VII": { "code": "BHS-102", "name": "Technical Writing & Professional Communication",
                        "type": "Practical" },
                    "VIII": { "code": "—", "name": "Self Study / Library", "type": "Free" } } },
            "me::A": { "Monday": { "I": { "code": "BSM-110", "name": "Engineering Mathematics I", "type": "Lecture" },
                    "II": { "code": "BEE-110", "name": "Basic Electrical Engineering", "type": "Lecture" },
                    "III": { "code": "BSM-140", "name": "Environmental Science & Green Chemistry",
                    "type": "Lecture" },
                    "IV": { "code": "BHS-102", "name": "Technical Writing & Professional Communication",
                        "type": "Lecture" },
                    "V": { "code": "BSM-140", "name": "Environmental Science & Green Chemistry",
                        "type": "Practical" },
                    "VI": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "VII": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "VIII": { "code": "BHS-102", "name": "Technical Writing & Professional Communication",
                        "type": "Tutorial" } },
                "Tuesday": { "I": { "code": "BME-104", "name": "Manufacturing Practice Workshop", "type": "Practical" },
                    "II": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "III": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "IV": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "V": { "code": "BSM-140", "name": "Environmental Science & Green Chemistry",
                        "type": "Practical" },
                    "VI": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "VII": { "code": "BSM-140", "name": "Environmental Science & Green Chemistry",
                        "type": "Lecture" },
                    "VIII": { "code": "BHS-102", "name": "Technical Writing & Professional Communication",
                        "type": "Tutorial" } },
                "Wednesday": { "I": { "code": "BSM-140", "name": "Environmental Science & Green Chemistry",
                        "type": "Lecture" },
                    "II": { "code": "BME-104", "name": "Manufacturing Practice Workshop", "type": "Lecture" },
                    "III": { "code": "BEE-110", "name": "Basic Electrical Engineering", "type": "Practical" },
                    "IV": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "V": { "code": "BEE-110", "name": "Basic Electrical Engineering", "type": "Practical" },
                    "VI": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "VII": { "code": "BHS-102", "name": "Technical Writing & Professional Communication",
                        "type": "Lecture" },
                    "VIII": { "code": "BSM-110", "name": "Engineering Mathematics I", "type": "Tutorial" } },
                "Thursday": { "I": { "code": "BSM-110", "name": "Engineering Mathematics I", "type": "Lecture" },
                    "II": { "code": "BEE-110", "name": "Basic Electrical Engineering", "type": "Lecture" },
                    "III": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "IV": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "V": { "code": "BME-104", "name": "Manufacturing Practice Workshop", "type": "Lecture" },
                    "VI": { "code": "BSM-110", "name": "Engineering Mathematics I", "type": "Tutorial" },
                    "VII": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "VIII": { "code": "—", "name": "Self Study / Library", "type": "Free" } },
                "Friday": { "I": { "code": "BSM-110", "name": "Engineering Mathematics I", "type": "Lecture" },
                    "II": { "code": "BEE-110", "name": "Basic Electrical Engineering", "type": "Lecture" },
                    "III": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "IV": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "V": { "code": "BME-104", "name": "Manufacturing Practice Workshop", "type": "Practical" },
                    "VI": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "VII": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "VIII": { "code": "—", "name": "Self Study / Library", "type": "Free" } } },
            "me::B": { "Monday": { "I": { "code": "BSM-140", "name": "Environmental Science & Green Chemistry",
                        "type": "Practical" },
                    "II": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "III": { "code": "BEE-110", "name": "Basic Electrical Engineering", "type": "Practical" },
                    "IV": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "V": { "code": "BSM-110", "name": "Engineering Mathematics I", "type": "Lecture" },
                    "VI": { "code": "BEE-110", "name": "Basic Electrical Engineering", "type": "Lecture" },
                    "VII": { "code": "BSM-110", "name": "Engineering Mathematics I", "type": "Tutorial" },
                    "VIII": { "code": "—", "name": "Self Study / Library", "type": "Free" } },
                "Tuesday": { "I": { "code": "BSM-110", "name": "Engineering Mathematics I", "type": "Lecture" },
                    "II": { "code": "BEE-110", "name": "Basic Electrical Engineering", "type": "Lecture" },
                    "III": { "code": "BSM-140", "name": "Environmental Science & Green Chemistry",
                    "type": "Lecture" },
                    "IV": { "code": "BME-104", "name": "Manufacturing Practice Workshop", "type": "Lecture" },
                    "V": { "code": "BME-104", "name": "Manufacturing Practice Workshop", "type": "Practical" },
                    "VI": { "code": "BHS-102", "name": "Technical Writing & Professional Communication",
                        "type": "Tutorial" },
                    "VII": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "VIII": { "code": "—", "name": "Self Study / Library", "type": "Free" } },
                "Wednesday": { "I": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "II": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "III": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "IV": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "V": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "VI": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "VII": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "VIII": { "code": "—", "name": "Self Study / Library", "type": "Free" } },
                "Thursday": { "I": { "code": "BEE-110", "name": "Basic Electrical Engineering", "type": "Practical" },
                    "II": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "III": { "code": "BSM-140", "name": "Environmental Science & Green Chemistry",
                        "type": "Lecture" },
                    "IV": { "code": "BME-104", "name": "Manufacturing Practice Workshop", "type": "Lecture" },
                    "V": { "code": "BHS-102", "name": "Technical Writing & Professional Communication",
                        "type": "Practical" },
                    "VI": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "VII": { "code": "BSM-110", "name": "Engineering Mathematics I", "type": "Tutorial" },
                    "VIII": { "code": "—", "name": "Self Study / Library", "type": "Free" } },
                "Friday": { "I": { "code": "BHS-102", "name": "Technical Writing & Professional Communication",
                        "type": "Practical" },
                    "II": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "III": { "code": "BSM-110", "name": "Engineering Mathematics I", "type": "Lecture" },
                    "IV": { "code": "BEE-110", "name": "Basic Electrical Engineering", "type": "Lecture" },
                    "V": { "code": "BSM-140", "name": "Environmental Science & Green Chemistry",
                        "type": "Practical" },
                    "VI": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "VII": { "code": "BHS-102", "name": "Technical Writing & Professional Communication",
                        "type": "Tutorial" },
                    "VIII": { "code": "—", "name": "Self Study / Library", "type": "Free" } } },
            "ece::A": { "Monday": { "I": { "code": "BSM-110", "name": "Engineering Mathematics I", "type": "Lecture" },
                    "II": { "code": "BEE-110", "name": "Basic Electrical Engineering", "type": "Lecture" },
                    "III": { "code": "BSM-140", "name": "Environmental Science & Green Chemistry",
                        "type": "Practical" },
                    "IV": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "V": { "code": "BHS-102", "name": "Technical Writing & Professional Communication",
                        "type": "Lecture" },
                    "VI": { "code": "BSM-140", "name": "Environmental Science & Green Chemistry",
                    "type": "Lecture" },
                    "VII": { "code": "BEE-110", "name": "Basic Electrical Engineering", "type": "Practical" },
                    "VIII": { "code": "—", "name": "Self Study / Library", "type": "Free" } },
                "Tuesday": { "I": { "code": "BEC-106", "name": "Electronic Components Testing & Measurement",
                        "type": "Practical" },
                    "II": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "III": { "code": "BSM-140", "name": "Environmental Science & Green Chemistry",
                        "type": "Practical" },
                    "IV": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "V": { "code": "BHS-102", "name": "Technical Writing & Professional Communication",
                        "type": "Lecture" },
                    "VI": { "code": "BSM-140", "name": "Environmental Science & Green Chemistry",
                    "type": "Lecture" },
                    "VII": { "code": "BEE-110", "name": "Basic Electrical Engineering", "type": "Practical" },
                    "VIII": { "code": "—", "name": "Self Study / Library", "type": "Free" } },
                "Wednesday": { "I": { "code": "BHS-102", "name": "Technical Writing & Professional Communication",
                        "type": "Practical" },
                    "II": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "III": { "code": "BSM-140", "name": "Environmental Science & Green Chemistry",
                        "type": "Lecture" },
                    "IV": { "code": "BEC-106", "name": "Electronic Components Testing & Measurement",
                    "type": "Lecture" },
                    "V": { "code": "BEC-106", "name": "Electronic Components Testing & Measurement",
                        "type": "Practical" },
                    "VI": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "VII": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "VIII": { "code": "—", "name": "Self Study / Library", "type": "Free" } },
                "Thursday": { "I": { "code": "BSM-110", "name": "Engineering Mathematics I", "type": "Lecture" },
                    "II": { "code": "BEE-110", "name": "Basic Electrical Engineering", "type": "Lecture" },
                    "III": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "IV": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "V": { "code": "BSM-110", "name": "Engineering Mathematics I", "type": "Tutorial" },
                    "VI": { "code": "BEC-106", "name": "Electronic Components Testing & Measurement",
                        "type": "Lecture" },
                    "VII": { "code": "BHS-102", "name": "Technical Writing & Professional Communication",
                        "type": "Tutorial" },
                    "VIII": { "code": "—", "name": "Self Study / Library", "type": "Free" } },
                "Friday": { "I": { "code": "BSM-110", "name": "Engineering Mathematics I", "type": "Lecture" },
                    "II": { "code": "BEE-110", "name": "Basic Electrical Engineering", "type": "Lecture" },
                    "III": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "IV": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "V": { "code": "BSM-110", "name": "Engineering Mathematics I", "type": "Tutorial" },
                    "VI": { "code": "BHS-102", "name": "Technical Writing & Professional Communication",
                        "type": "Tutorial" },
                    "VII": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "VIII": { "code": "—", "name": "Self Study / Library", "type": "Free" } } },
            "ece::B": { "Monday": { "I": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "II": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "III": { "code": "BEC-106", "name": "Electronic Components Testing & Measurement",
                        "type": "Lecture" },
                    "IV": { "code": "BSM-140", "name": "Environmental Science & Green Chemistry",
                    "type": "Lecture" },
                    "V": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "VI": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "VII": { "code": "BSM-110", "name": "Engineering Mathematics I", "type": "Tutorial" },
                    "VIII": { "code": "BHS-102", "name": "Technical Writing & Professional Communication",
                        "type": "Tutorial" } },
                "Tuesday": { "I": { "code": "BEE-110", "name": "Basic Electrical Engineering", "type": "Lecture" },
                    "II": { "code": "BSM-110", "name": "Engineering Mathematics I", "type": "Lecture" },
                    "III": { "code": "BHS-102", "name": "Technical Writing & Professional Communication",
                        "type": "Lecture" },
                    "IV": { "code": "BSM-140", "name": "Environmental Science & Green Chemistry",
                    "type": "Lecture" },
                    "V": { "code": "BHS-102", "name": "Technical Writing & Professional Communication",
                        "type": "Practical" },
                    "VI": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "VII": { "code": "BEC-106", "name": "Electronic Components Testing & Measurement",
                        "type": "Lecture" },
                    "VIII": { "code": "—", "name": "Self Study / Library", "type": "Free" } },
                "Wednesday": { "I": { "code": "BEE-110", "name": "Basic Electrical Engineering", "type": "Lecture" },
                    "II": { "code": "BSM-110", "name": "Engineering Mathematics I", "type": "Lecture" },
                    "III": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "IV": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "V": { "code": "BHS-102", "name": "Technical Writing & Professional Communication",
                        "type": "Practical" },
                    "VI": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "VII": { "code": "BHS-102", "name": "Technical Writing & Professional Communication",
                        "type": "Lecture" },
                    "VIII": { "code": "BSM-140", "name": "Environmental Science & Green Chemistry",
                        "type": "Lecture" } },
                "Thursday": { "I": { "code": "BSM-140", "name": "Environmental Science & Green Chemistry",
                        "type": "Practical" },
                    "II": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "III": { "code": "BSM-110", "name": "Engineering Mathematics I", "type": "Tutorial" },
                    "IV": { "code": "BHS-102", "name": "Technical Writing & Professional Communication",
                        "type": "Tutorial" },
                    "V": { "code": "BEE-110", "name": "Basic Electrical Engineering", "type": "Practical" },
                    "VI": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "VII": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "VIII": { "code": "—", "name": "Self Study / Library", "type": "Free" } },
                "Friday": { "I": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "II": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "III": { "code": "BSM-110", "name": "Engineering Mathematics I", "type": "Lecture" },
                    "IV": { "code": "BEE-110", "name": "Basic Electrical Engineering", "type": "Lecture" },
                    "V": { "code": "BEE-110", "name": "Basic Electrical Engineering", "type": "Practical" },
                    "VI": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "VII": { "code": "BSM-140", "name": "Environmental Science & Green Chemistry",
                        "type": "Practical" },
                    "VIII": { "code": "—", "name": "Self Study / Library", "type": "Free" } } },
            "ece::C": { "Monday": { "I": { "code": "BEE-110", "name": "Basic Electrical Engineering",
                        "type": "Practical" },
                    "II": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "III": { "code": "BHS-102", "name": "Technical Writing & Professional Communication",
                        "type": "Practical" },
                    "IV": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "V": { "code": "BSM-110", "name": "Engineering Mathematics I", "type": "Lecture" },
                    "VI": { "code": "BSM-140", "name": "Environmental Science & Green Chemistry",
                    "type": "Lecture" },
                    "VII": { "code": "BHS-102", "name": "Technical Writing & Professional Communication",
                        "type": "Lecture" },
                    "VIII": { "code": "—", "name": "Self Study / Library", "type": "Free" } },
                "Tuesday": { "I": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "II": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "III": { "code": "BEE-110", "name": "Basic Electrical Engineering", "type": "Lecture" },
                    "IV": { "code": "BEC-106", "name": "Electronic Components Testing & Measurement",
                        "type": "Lecture" },
                    "V": { "code": "BEC-106", "name": "Electronic Components Testing & Measurement",
                        "type": "Practical" },
                    "VI": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "VII": { "code": "BSM-140", "name": "Environmental Science & Green Chemistry",
                        "type": "Practical" },
                    "VIII": { "code": "—", "name": "Self Study / Library", "type": "Free" } },
                "Wednesday": { "I": { "code": "BEC-106", "name": "Electronic Components Testing & Measurement",
                        "type": "Lecture" },
                    "II": { "code": "BEE-110", "name": "Basic Electrical Engineering", "type": "Lecture" },
                    "III": { "code": "BSM-140", "name": "Environmental Science & Green Chemistry",
                        "type": "Practical" },
                    "IV": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "V": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "VI": { "code": "BSM-110", "name": "Engineering Mathematics I", "type": "Tutorial" },
                    "VII": { "code": "BHS-102", "name": "Technical Writing & Professional Communication",
                        "type": "Tutorial" },
                    "VIII": { "code": "—", "name": "Self Study / Library", "type": "Free" } },
                "Thursday": { "I": { "code": "BSM-110", "name": "Engineering Mathematics I", "type": "Lecture" },
                    "II": { "code": "BSM-140", "name": "Environmental Science & Green Chemistry",
                    "type": "Lecture" },
                    "III": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "IV": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "V": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "VI": { "code": "BSM-110", "name": "Engineering Mathematics I", "type": "Tutorial" },
                    "VII": { "code": "BHS-102", "name": "Technical Writing & Professional Communication",
                        "type": "Tutorial" },
                    "VIII": { "code": "—", "name": "Self Study / Library", "type": "Free" } },
                "Friday": { "I": { "code": "BSM-110", "name": "Engineering Mathematics I", "type": "Lecture" },
                    "II": { "code": "BSM-140", "name": "Environmental Science & Green Chemistry",
                    "type": "Lecture" },
                    "III": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "IV": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "V": { "code": "BHS-102", "name": "Technical Writing & Professional Communication",
                        "type": "Lecture" },
                    "VI": { "code": "BEE-110", "name": "Basic Electrical Engineering", "type": "Lecture" },
                    "VII": { "code": "BEE-110", "name": "Basic Electrical Engineering", "type": "Practical" },
                    "VIII": { "code": "—", "name": "Self Study / Library", "type": "Free" } } },
            "eceiot::A": { "Monday": { "I": { "code": "BSM-110", "name": "Engineering Mathematics I",
                        "type": "Lecture" },
                    "II": { "code": "BSM-140", "name": "Environmental Science & Green Chemistry",
                    "type": "Lecture" },
                    "III": { "code": "BEC-106", "name": "Electronic Components Testing & Measurement",
                        "type": "Lecture" },
                    "IV": { "code": "BEE-110", "name": "Basic Electrical Engineering", "type": "Lecture" },
                    "V": { "code": "BEE-110", "name": "Basic Electrical Engineering", "type": "Practical" },
                    "VI": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "VII": { "code": "BHS-102", "name": "Technical Writing & Professional Communication",
                        "type": "Practical" },
                    "VIII": { "code": "—", "name": "Self Study / Library", "type": "Free" } },
                "Tuesday": { "I": { "code": "BSM-110", "name": "Engineering Mathematics I", "type": "Lecture" },
                    "II": { "code": "BSM-140", "name": "Environmental Science & Green Chemistry",
                    "type": "Lecture" },
                    "III": { "code": "BHS-102", "name": "Technical Writing & Professional Communication",
                        "type": "Lecture" },
                    "IV": { "code": "BEE-110", "name": "Basic Electrical Engineering", "type": "Lecture" },
                    "V": { "code": "BHS-102", "name": "Technical Writing & Professional Communication",
                        "type": "Tutorial" },
                    "VI": { "code": "BSM-110", "name": "Engineering Mathematics I", "type": "Tutorial" },
                    "VII": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "VIII": { "code": "—", "name": "Self Study / Library", "type": "Free" } },
                "Wednesday": { "I": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "II": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "III": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "IV": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "V": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "VI": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "VII": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "VIII": { "code": "—", "name": "Self Study / Library", "type": "Free" } },
                "Thursday": { "I": { "code": "BHS-102", "name": "Technical Writing & Professional Communication",
                        "type": "Practical" },
                    "II": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "III": { "code": "BSM-110", "name": "Engineering Mathematics I", "type": "Lecture" },
                    "IV": { "code": "BSM-140", "name": "Environmental Science & Green Chemistry",
                    "type": "Lecture" },
                    "V": { "code": "BSM-140", "name": "Environmental Science & Green Chemistry",
                        "type": "Practical" },
                    "VI": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "VII": { "code": "BEE-110", "name": "Basic Electrical Engineering", "type": "Practical" },
                    "VIII": { "code": "—", "name": "Self Study / Library", "type": "Free" } },
                "Friday": { "I": { "code": "BSM-140", "name": "Environmental Science & Green Chemistry",
                        "type": "Practical" },
                    "II": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "III": { "code": "BEC-106", "name": "Electronic Components Testing & Measurement",
                        "type": "Lecture" },
                    "IV": { "code": "BEE-110", "name": "Basic Electrical Engineering", "type": "Lecture" },
                    "V": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "VI": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "VII": { "code": "BSM-110", "name": "Engineering Mathematics I", "type": "Tutorial" },
                    "VIII": { "code": "BHS-102", "name": "Technical Writing & Professional Communication",
                        "type": "Tutorial" } } },
            "bba::A": { "Monday": { "I": { "code": "BBA-115", "name": "Principles & Practices of Management",
                        "type": "Tutorial" },
                    "II": { "code": "BBA-114", "name": "Financial Accounting", "type": "Lecture" },
                    "III": { "code": "BBA-116", "name": "Quantitative Techniques for Business Research",
                        "type": "Tutorial" },
                    "IV": { "code": "BBA-114", "name": "Financial Accounting", "type": "Tutorial" },
                    "V": { "code": "BHM-121", "name": "Industrial Psychology", "type": "Tutorial" },
                    "VI": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "VII": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "VIII": { "code": "—", "name": "Self Study / Library", "type": "Free" } },
                "Tuesday": { "I": { "code": "BHM-121", "name": "Industrial Psychology", "type": "Lecture" },
                    "II": { "code": "BBA-114", "name": "Financial Accounting", "type": "Lecture" },
                    "III": { "code": "BBA-114", "name": "Financial Accounting", "type": "Tutorial" },
                    "IV": { "code": "BBA-115", "name": "Principles & Practices of Management", "type": "Lecture" },
                    "V": { "code": "BBA-A01", "name": "Business Communication for Managers", "type": "Lecture" },
                    "VI": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "VII": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "VIII": { "code": "—", "name": "Self Study / Library", "type": "Free" } },
                "Wednesday": { "I": { "code": "BHM-121", "name": "Industrial Psychology", "type": "Lecture" },
                    "II": { "code": "BBA-114", "name": "Financial Accounting", "type": "Lecture" },
                    "III": { "code": "BBA-116", "name": "Quantitative Techniques for Business Research",
                        "type": "Tutorial" },
                    "IV": { "code": "BBA-115", "name": "Principles & Practices of Management", "type": "Tutorial" },
                    "V": { "code": "BBA-116", "name": "Quantitative Techniques for Business Research",
                        "type": "Lecture" },
                    "VI": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "VII": { "code": "BHM-121", "name": "Industrial Psychology", "type": "Tutorial" },
                    "VIII": { "code": "—", "name": "Self Study / Library", "type": "Free" } },
                "Thursday": { "I": { "code": "BHM-121", "name": "Industrial Psychology", "type": "Lecture" },
                    "II": { "code": "AUC-108", "name": "Intellectual Property Rights", "type": "Lecture" },
                    "III": { "code": "BBA-A01", "name": "Business Communication for Managers", "type": "Tutorial" },
                    "IV": { "code": "BBA-115", "name": "Principles & Practices of Management", "type": "Lecture" },
                    "V": { "code": "BBA-116", "name": "Quantitative Techniques for Business Research",
                        "type": "Lecture" },
                    "VI": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "VII": { "code": "BBA-A01", "name": "Business Communication for Managers", "type": "Lecture" },
                    "VIII": { "code": "—", "name": "Self Study / Library", "type": "Free" } },
                "Friday": { "I": { "code": "BBA-A01", "name": "Business Communication for Managers",
                        "type": "Lecture" },
                    "II": { "code": "AUC-108", "name": "Intellectual Property Rights", "type": "Lecture" },
                    "III": { "code": "BBA-A01", "name": "Business Communication for Managers", "type": "Tutorial" },
                    "IV": { "code": "BBA-115", "name": "Principles & Practices of Management", "type": "Lecture" },
                    "V": { "code": "BBA-116", "name": "Quantitative Techniques for Business Research",
                        "type": "Lecture" },
                    "VI": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "VII": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "VIII": { "code": "—", "name": "Self Study / Library", "type": "Free" } } },
            "bba::B": { "Monday": { "I": { "code": "BBA-114", "name": "Financial Accounting", "type": "Tutorial" },
                    "II": { "code": "BBA-116", "name": "Quantitative Techniques for Business Research",
                        "type": "Lecture" },
                    "III": { "code": "BHM-121", "name": "Industrial Psychology", "type": "Lecture" },
                    "IV": { "code": "BBA-115", "name": "Principles & Practices of Management", "type": "Tutorial" },
                    "V": { "code": "BBA-A01", "name": "Business Communication for Managers", "type": "Lecture" },
                    "VI": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "VII": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "VIII": { "code": "—", "name": "Self Study / Library", "type": "Free" } },
                "Tuesday": { "I": { "code": "AUC-108", "name": "Intellectual Property Rights", "type": "Lecture" },
                    "II": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "III": { "code": "BHM-121", "name": "Industrial Psychology", "type": "Tutorial" },
                    "IV": { "code": "BBA-114", "name": "Financial Accounting", "type": "Lecture" },
                    "V": { "code": "BBA-115", "name": "Principles & Practices of Management", "type": "Lecture" },
                    "VI": { "code": "BBA-A01", "name": "Business Communication for Managers", "type": "Lecture" },
                    "VII": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "VIII": { "code": "—", "name": "Self Study / Library", "type": "Free" } },
                "Wednesday": { "I": { "code": "BHM-121", "name": "Industrial Psychology", "type": "Lecture" },
                    "II": { "code": "BBA-116", "name": "Quantitative Techniques for Business Research",
                        "type": "Lecture" },
                    "III": { "code": "BBA-114", "name": "Financial Accounting", "type": "Tutorial" },
                    "IV": { "code": "BBA-114", "name": "Financial Accounting", "type": "Lecture" },
                    "V": { "code": "BHM-121", "name": "Industrial Psychology", "type": "Tutorial" },
                    "VI": { "code": "BBA-A01", "name": "Business Communication for Managers", "type": "Tutorial" },
                    "VII": { "code": "AUC-108", "name": "Intellectual Property Rights", "type": "Lecture" },
                    "VIII": { "code": "—", "name": "Self Study / Library", "type": "Free" } },
                "Thursday": { "I": { "code": "BBA-115", "name": "Principles & Practices of Management",
                        "type": "Lecture" },
                    "II": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "III": { "code": "BBA-114", "name": "Financial Accounting", "type": "Lecture" },
                    "IV": { "code": "BBA-116", "name": "Quantitative Techniques for Business Research",
                        "type": "Tutorial" },
                    "V": { "code": "BBA-115", "name": "Principles & Practices of Management", "type": "Lecture" },
                    "VI": { "code": "BBA-A01", "name": "Business Communication for Managers", "type": "Tutorial" },
                    "VII": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "VIII": { "code": "—", "name": "Self Study / Library", "type": "Free" } },
                "Friday": { "I": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "II": { "code": "BHM-121", "name": "Industrial Psychology", "type": "Lecture" },
                    "III": { "code": "BBA-116", "name": "Quantitative Techniques for Business Research",
                        "type": "Lecture" },
                    "IV": { "code": "BBA-116", "name": "Quantitative Techniques for Business Research",
                        "type": "Tutorial" },
                    "V": { "code": "BBA-115", "name": "Principles & Practices of Management", "type": "Tutorial" },
                    "VI": { "code": "BBA-A01", "name": "Business Communication for Managers", "type": "Lecture" },
                    "VII": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "VIII": { "code": "—", "name": "Self Study / Library", "type": "Free" } } },
            "bpharm::A": { "Monday": { "I": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "II": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "III": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "IV": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "V": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "VI": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "VII": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "VIII": { "code": "—", "name": "Self Study / Library", "type": "Free" } },
                "Tuesday": { "I": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "II": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "III": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "IV": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "V": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "VI": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "VII": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "VIII": { "code": "—", "name": "Self Study / Library", "type": "Free" } },
                "Wednesday": { "I": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "II": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "III": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "IV": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "V": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "VI": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "VII": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "VIII": { "code": "—", "name": "Self Study / Library", "type": "Free" } },
                "Thursday": { "I": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "II": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "III": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "IV": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "V": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "VI": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "VII": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "VIII": { "code": "—", "name": "Self Study / Library", "type": "Free" } },
                "Friday": { "I": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "II": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "III": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "IV": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "V": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "VI": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "VII": { "code": "—", "name": "Self Study / Library", "type": "Free" },
                    "VIII": { "code": "—", "name": "Self Study / Library", "type": "Free" } } }
        };
